language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-9.0
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
bundler_args: --without development
