language: ruby
sudo: false
rvm:
  - 2.2
  - 2.1
  - 2.0
  - jruby-9.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
bundler_args: --without development
